# Generated by Django 2.2.12 on 2021-08-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_apointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='High_admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=100)),
                ('student_phone_no', models.CharField(max_length=12, null=True)),
                ('student_class', models.CharField(max_length=100, null=True)),
                ('student_text_area', models.TextField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pri_admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=100)),
                ('student_phone_no', models.CharField(max_length=12, null=True)),
                ('student_class', models.CharField(max_length=100, null=True)),
                ('student_text_area', models.TextField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Re_admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=100)),
                ('student_phone_no', models.CharField(max_length=12, null=True)),
                ('student_class', models.CharField(max_length=100, null=True)),
                ('student_text_area', models.TextField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
