# Generated by Django 2.2.12 on 2021-08-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_high_admission_pri_admission_re_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='high_admission',
            name='student_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='high_admission',
            name='student_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pri_admission',
            name='student_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pri_admission',
            name='student_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='re_admission',
            name='student_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='re_admission',
            name='student_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
